# KaGuilds 配置文件
language: zh_CN  # en_US 或 zh_CN

proxy: false # 是否启用代理模式
server-id: server # 服务器名称，用于跨服邀请/通讯
date-format: "yyyy-MM-dd HH:mm:ss"

guild:
  name-settings: # 名称设置
    min-length: 3
    max-length: 16
    # 正则表达式：允许英文字母、数字、下划线、汉字
    regex: "^[\\u4e00-\\u9fa5a-zA-Z0-9]+$"
  motd: "欢迎加入我的公会"
  icon: "SHIELD"
  buff-time: 90 # 公会buff时间(秒)
  teleport: # 传送设置
    disabled-worlds: # 禁止设置传送点的世界
      - "world_nether"
      - "world_the_end"
    cooldown: 3 # 传送时间(秒)
  arena:
    cooldown: 300 # 公会战冷却时间(秒)
    min-players: 2 # 队伍最小人数
    max-players: 10 # 队伍最大人数
    ready-time: 120 # 公会战准备时间(秒)
    pvp-time: 600 # 公会战游戏时间(秒)
    kit: true # 是否启用套装
    reward-command:
      - 'kg admin bank {id} add 1000' # 公会战奖励,{id}为胜利公会id
      - 'kg admin exp {id} add 500'

database:
  # 数据库类型: MySQL 或 SQLite
  type: "SQLite"
  host: "localhost"
  port: 3306
  db: "kaguilds"
  user: "root"
  password: "password"

# 经济系统设置
balance:
  create: 10000.0  # 创建公会所需金币
  rename: 3000.0  # 公会改名所需金币
  settp: 1000.0  # 设置传送点所需金币
  seticon: 1000.0  # 设置公会图标所需金币
  motd: 100.0  # 设置公会公告所需金币
  pvp: 300.0 # 发起公会战所需金币


