# KaGuilds 配置文件
language: en_US  # en_US 或 zh_CN

database:
  # 数据库类型: MySQL 或 SQLite
  type: "SQLite"
  host: "localhost"
  port: 3306
  db: "kaguilds"
  user: "root"
  password: "password"

# 经济系统设置
balance:
  create: 10000.0  # 创建公会所需金币

level: # 公会等级设置
  1:
    need-exp: 0 # 公会等级1需要的经验值，默认1级
    max-members: 10 # 公会最大人数
    max-money: 50000 # 公会金库最大金币
  2:
    need-exp: 5000 # 公会等级2需要的经验值
    max-members: 20 # 公会最大人数
    max-money: 100000 # 公会金库最大金币
