# KaGuilds 配置文件
language: zh_CN  # en_US 或 zh_CN

proxy: false # 是否启用代理模式
server-name: server # 服务器名称，用于跨服邀请/通讯

guild:
  name:
    min-length: 3
    max-length: 16
    # 正则表达式：允许英文字母、数字、下划线、汉字
    regex: "^[a-zA-Z0-9_\\u4e00-\\u9fa5]+$"

database:
  # 数据库类型: MySQL 或 SQLite
  type: "SQLite"
  host: "localhost"
  port: 3306
  db: "kaguilds"
  user: "root"
  password: "password"

# 经济系统设置
balance:
  create: 10000.0  # 创建公会所需金币

level: # 公会等级设置
  1:
    need-exp: 0 # 公会等级1需要的经验值，默认1级
    max-members: 10 # 公会最大人数
    max-money: 50000 # 公会金库最大金币
    tp-money: 500 # 传送费用，等级越高费用越便宜
  2:
    need-exp: 5000 # 公会等级2需要的经验值
    max-members: 20 # 公会最大人数
    max-money: 100000 # 公会金库最大金币
    tp-money: 300 # 传送费用，等级越高费用越便宜
  3:
    need-exp: 10000 # 公会等级3需要的经验值
    max-members: 30 # 公会最大人数
    max-money: 200000 # 公会金库最大金币
    tp-money: 200 # 传送费用，等级越高费用越便宜
  4:
    need-exp: 20000 # 公会等级4需要的经验值
    max-members: 40 # 公会最大人数
    max-money: 400000 # 公会金库最大金币
    tp-money: 100 # 传送费用，等级越高费用越便宜
  5:
    need-exp: 50000 # 公会等级5需要的经验值
    max-members: 50 # 公会最大人数
    max-money: 600000 # 公会金库最大金币
    tp-money: 50 # 传送费用，等级越高费用越便宜
